### ISSUE TITLE
ValueError: Namespace Gst not available

### ISSUE THREAD

**Issue by lytex** [jordanpatterson1939/pi-clock#6]
The sound library is not working properly:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/julian/.local/bin/piclock", line 54, in playaudio_wrapper
    playsound(soundfile)
  File "/home/julian/.local/lib/python3.8/site-packages/playsound.py", line 92, in _playsoundNix
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
```

**Comment by lytex** [comment]
`sudo apt install python3-gst-1.0 ` fixes the issue (from https://stackoverflow.com/questions/40246437/problems-with-gst-in-python-program)
